# Generated by Django 4.0.5 on 2022-06-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_trains_datee_alter_trains_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
