# Generated by Django 4.0.5 on 2022-06-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_remove_person_age_remove_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='train_id',
            field=models.IntegerField(default=1),
        ),
    ]
