# Generated by Django 4.0.5 on 2022-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_trains_train_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=50)),
                ('Seat', models.CharField(max_length=50)),
                ('Coach', models.CharField(max_length=50)),
                ('datee', models.DateField(default='2022-06-11')),
            ],
        ),
        migrations.RemoveField(
            model_name='trains',
            name='train_id',
        ),
    ]
