# Generated by Django 4.0.5 on 2022-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_seats_remove_trains_train_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='status',
            field=models.CharField(default='y', max_length=50),
        ),
    ]
