# Generated by Django 4.0.5 on 2022-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_alter_trains_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='tid',
            field=models.IntegerField(default=1),
        ),
    ]
