# Generated by Django 4.0.4 on 2022-06-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_trains_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='status',
            field=models.CharField(default='y', max_length=50),
        ),
    ]
