# Generated by Django 4.0.4 on 2022-06-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_trains_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pay_check',
            field=models.IntegerField(default=0),
        ),
    ]
